name: seahorse
description:

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  #c
  cupertino_icons: ^1.0.8
  #d
  dio: 5.7.0
  #f
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.3
  #g
  get_it: 8.0.0
  go_router: 14.3.0
  #i
  input_quantity: 2.4.1
  intl: 0.19.0
  #j
  json_annotation: 4.9.0
  #r
  realm: 20.0.0
  retrofit: 4.4.1
  riverpod_annotation: 2.5.3

dev_dependencies:
  #b
  build_runner: 2.4.13
  #f
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  #j
  json_serializable: 6.8.0
  #r
  retrofit_generator: ^9.1.3
  riverpod_generator: 2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/stubs/products.json
